### ISSUE TITLE
Feature request: signals to be logged

### ISSUE THREAD

**Issue by S-Dafarra** [ami-iit/yarp-openmct#121]
In order to improve the usability of the framework, I think it would be important to add this set of data to be logged:
- [x] #122
    - ``position``
    - ``velocity``
    - ``acceleration``
    - ``torque``
- [x] #123
    - ``position``
    - ``velocity``
    - ``acceleration``
    - ``current``
    - ``pwm``
- [x] #124
    - ``rpy``
    - ``gyro``
    - ``accelerometer``
- [x] #125
- [x] #126 
    - ``FT``
- [x] #141
    - ``temperature``
- [x] #139
- [x] #138
- [x] #133
- ~#137~ Moved out of the Epic.

This is the list of things we are currently logging for offline testing. Reference code: https://github.com/ami-iit/bipedal-locomotion-framework/tree/dc113093d2467e854a2b1427265af55f559f13d0/devices/YarpRobotLoggerDevice

Let me remark that this data might be robot-dependent. For example, the lists of ``FT``s and ``cartesian_wrenches`` depend on the robot.

Moreover, we might need to add more data in the future.

cc @nunoguedelha @traversaro

**Comment by S-Dafarra** [comment]
It might also be useful to log the text log coming from the modules. In general anyway, it would be nice to have a shared interface between the online and offline logging. 

cc @GiulioRomualdi

**Comment by GiulioRomualdi** [comment]
For the TextLogging I took inspiration from what is done in YarpManager. https://github.com/ami-iit/bipedal-locomotion-framework/pull/546

**Comment by nunoguedelha** [comment]
> For the TextLogging I took inspiration from what is done in YarpManager. [ami-iit/bipedal-locomotion-framework#546](https://github.com/ami-iit/bipedal-locomotion-framework/pull/546)

@GiulioRomualdi , I guess you meant more specifically https://github.com/ami-iit/bipedal-locomotion-framework/pull/541.

**Comment by nunoguedelha** [comment]
@S-Dafarra , I've added the following bullets/issues in the description according to your comments:
- [ ] Improve the handling of the robot dependant configuration
- [ ] Add the possibility to log the YarpTextLogging

**Comment by nunoguedelha** [comment]
@S-Dafarra , I had already added #133 to this epic, and just added it to the issue description.

Also added the issue #139 fixing the problems we ran into during the last test session on Friday.

**Comment by nunoguedelha** [comment]
If it's ok with you @S-Dafarra , I would close this Epic.

**Comment by S-Dafarra** [comment]
I agree. Great work!
