### ISSUE TITLE
Prepare training sessions with candidate future owner(s)

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/yarp-openmct#158]

**Comment by S-Dafarra** [comment]
The training has been performed. I have shared the link to the recordings with @FrancescaBruzzone. We will upload them on youtube unlisted.

@FrancescaBruzzone if you could please share the link, then we can close this.

**Comment by FrancescaBruzzone** [comment]
Here the link to the videos
https://youtu.be/jz_vnFYgoTo
https://youtu.be/JVbaE2kksS0
@S-Dafarra

**Comment by S-Dafarra** [comment]
Awesome! Thanks @FrancescaBruzzone and @nunoguedelha
 Closing
