### ISSUE TITLE
Add iFeel suit ports to the telemetry server and respective entries in the visualizer GUI

### ISSUE THREAD

**Issue by nunoguedelha** [ami-iit/yarp-openmct#43]
We discussed with @RiccardoGrieco on the requirements for visualizing the iFeel suit sensor information within the Open-CT based visualizer tool. We recap below a quick guide on how to add a new telemetry data source Yarp port to the modules `iCubTelemVizServer` and `openmctStaticServer`:

(throughout the following description, we shall use the IMU measurements entry as an example)
![image.png](https://images.zenhubusercontent.com/5977321361b4ca3b0a759709/3036e0fa-d19a-4c9b-bad1-19ea33a18573)

- In `iCubTelemVizServer/iCubTelemVizServer.js`: add the port configuration entry in the `portInConfig` JSON string<sup>(*)</sup> (fields: port Yarp and local names, data type).
   ```js
   var portInConfig = {
       "sens.imu": {"yarpName":'/icubSim/inertial', "localName":'/yarpjs/inertial:i',"portType":'bottle'},
       ...
   }
   ```
- In `iCubTelemVizServer/icubtelemetry.js`:
    - Add a new entry to the JSON string `this.state` in the constructor `ICubTelemetry`, the internal buffer where we store the samples read from YARP and parsed.
    - The new entry is key/value pair where the key is the chosen **id** of the telemetry entry, and the value is a number or a nested JSON string holding the signal sub-fields. The same **id** shall be used in the `dictionary.js` defining the telemetry entries in the visualizer client.
       ```js
       this.state = {
           "sens.imu": {
             "ori": {"roll": 0, "pitch": 0, "yaw": 0},
             "acc": {"x": 0, "y": 0, "z": 0},
             "gyr": {"x": 0, "y": 0, "z": 0},
             "mag": {"x": 0, "y": 0, "z": 0}
           },
           ...
       }
       ```
    - Add the data parser to `ICubTelemetry.prototype.updateState`.
       ```js
       switch(id) {
           case "sens.imu":
               this.state[id].ori.roll = sensorSample[0];
               this.state[id].ori.pitch = sensorSample[1];
               ...
       }
       ```
    - If the entry in `this.state` has nested structures, it has to be flattened during the telemetry sample generation in `ICubTelemetry.prototype.generateTelemetry`: add the entry **id** in the switch case which applies `this.flatten()`.
       ```js
       switch(id) {
           case "sens.imu":
           case "sens.leftLegState":
           case "sens.leftLegEEwrench":
           case "sens.rightLegEEwrench":
           case "sens.batteryStatus":
               var telemetrySample = this.flatten({timestamp: timestamp, value: value, id: id});
               break;
           default:
               var telemetrySample = {timestamp: timestamp, value: value, id: id};
       }
       ```
- In `openmctStaticServer/dictionry.json` (defines th telemetry entries in the visualizer web interface):
    - Add a new entry in the measurements list `"measurements"`<sup>(**)</sup>. The format should be as follows, for the IMU measurements example:
       ```js
       {
         "name": "iCub Telemetry",
         "key": "sc",
         "measurements": [
           {
             "name": "IMU sensor measurements",
             "key": "sens.imu",
             "values": [
               {
                 "key": "value.ori.roll",
                 "name": "Roll",
                 "units": "degrees",
                 "format": "float",
                 "hints": {
                   "range": 1
                 }
               },
               ...
               {
                 "key": "utc",
                 "source": "timestamp",
                 "name": "Timestamp",
                 "format": "utc",
                 "hints": {
                   "domain": 1
                 }
               }
             ]
           },
           ...
         ]
       }
       ```
    - In this example, `"sens.imu"`is the same **id** used in the `this.state` entry.
    - Blocks having the `"hints": {"range": x}` assign the measurement component to the Y axis, while blocks having the `"hints": {"domain": x}` assign the component to the X axis.
    - The key for each measurement component is the concatenation of keys to reach that component in the internal buffer variable `this.state`.
    - In `"hints": {"range": x}`, "x" is the order of appearence in the Y axis drop down menu.
    ![image.png](https://images.zenhubusercontent.com/5977321361b4ca3b0a759709/7c158093-4a6f-4730-8e4a-0e862123b0df)

(*) A JSON  string is a string containing nested JSON object literals. A JSON object literal is a list of key/value pairs. Refer to https://www.w3schools.com/js/js_json_objects.asp.
(**) In this example the IMU measurements are included in the group `"iCub Telemetry"` but you can create a new group of measurements where to add your new telemetry entries.

**Comment by nunoguedelha** [comment]
Hi @RiccardoGrieco , let me know if I left some point obscure of it's clear enough, or feel free to amend the guide yourself.

**Comment by nunoguedelha** [comment]
CC @evalli-iit , @lrapetti , @S-Dafarra , @traversaro

**Comment by nunoguedelha** [comment]
Ciao @RiccardoGrieco , could you please give me the following info:
- port name(s) publishing the iFeel data
- info on the data...
    - If it uses a Multiple Analog Sensor wrapper, the device wrapper configuration files should be enough, OR
    - if it uses any other wrapper, I need the details on the data structure and types (double, string, etc) and/or YARP device (wrapper) name (or class) publishing the data + respective config files.

**Comment by RiccardoGrieco** [comment]
At the following link the definition of the messages: https://github.com/robotology/wearables/blob/b9a6fe404b837e1b594c89ac1a1ac37dd46a1567/msgs/thrift/WearableData.thrift#L173-L191

Attached instead there is the output of yarp read. The port is`/iFeelSuit/WearableData/data:o`.

[iFeelSuitMessages.txt](https://github.com/ami-iit/yarp-openmct/files/9709178/iFeelSuitMessages.txt)

**Comment by RiccardoGrieco** [comment]
A small dataset that can be replayed with `yarpdataplayer --withExtraTimeCol 2`

[ifeel_data.zip](https://github.com/ami-iit/yarp-openmct/files/9714389/ifeel_data.zip)

**Comment by nunoguedelha** [comment]
@RiccardoGrieco , I would have a few questions regarding the format file. Below I mention the higher structure and as an example the Accelerometer structure:
https://github.com/robotology/wearables/blob/b9a6fe404b837e1b594c89ac1a1ac37dd46a1567/msgs/thrift/WearableData.thrift#L173-L191
```
struct WearableData {
1: required string producerName;
2: optional map<string,Accelerometer> accelerometers;
3: optional map<string,EmgSensor> emgSensors;
4: optional map<string,Force3DSensor> force3DSensors;
5: optional map<string,ForceTorque6DSensor> forceTorque6DSensors;
6: optional map<string,FreeBodyAccelerationSensor> freeBodyAccelerationSensors;
7: optional map<string,Gyroscope> gyroscopes;
8: optional map<string,Magnetometer> magnetometers;
9: optional map<string,OrientationSensor> orientationSensors;
10: optional map<string,PoseSensor> poseSensors;
11: optional map<string,PositionSensor> positionSensors;
12: optional map<string,SkinSensor> skinSensors;
13: optional map<string,TemperatureSensor> temperatureSensors;
14: optional map<string,Torque3DSensor> torque3DSensors;
15: optional map<string,VirtualLinkKinSensor> virtualLinkKinSensors;
16: optional map<string,VirtualJointKinSensor> virtualJointKinSensors;
17: optional map<string,VirtualSphericalJointKinSensor> virtualSphericalJointKinSensors;
}
```
https://github.com/robotology/wearables/blob/b9a6fe404b837e1b594c89ac1a1ac37dd46a1567/msgs/thrift/WearableData.thrift#L89-L92
```
struct Accelerometer {
  1: SensorInfo info;
  2: VectorXYZ data;
}
```
https://github.com/robotology/wearables/blob/b9a6fe404b837e1b594c89ac1a1ac37dd46a1567/msgs/thrift/WearableData.thrift#L17-L20
```
struct SensorInfo{
  1: string name;
  2: SensorStatus status = SensorStatus.UNKNOWN;
}
```

- Are the higher level map key and the `SensorInfo.name` always the same on the currently streamed data?
- If that's the case, out of curiosity, why the redundancy?
- Why not just use n array of `Accelerometer` structures, or the `Accelerometer` structure have only the `status` and `data`?

**Comment by nunoguedelha** [comment]
Sure, it was just for my understanding. It's pretty clear, thanks @lrapetti .

**Comment by nunoguedelha** [comment]
##  Add the iFeel suit telemetry dictionary main entry and sub-folders (empty for now)

![image](https://user-images.githubusercontent.com/6848872/195653686-332b2056-9088-440b-9a1a-09e7b7009362.png)

Commit 80036a9f2ddf0e3d876ced686dc88c301a9960ab.

#### Dictionary structure
```
  "name": "iFeel Suit Telemetry",
  "key": "iFeelSuitTelemetry",
  ...
  "telemetryEntries": [
    {
      "name": "Accelerometers",
      "key": "accSens",
      "type": "folder",
      "telemetryEntries": []
    },
    {
      "name": "EMG Sensors",
      "key": "emgSens",
      "type": "folder",
      "telemetryEntries": []
    },
    ...
  ]
```

**Comment by nunoguedelha** [comment]
Edited https://github.com/ami-iit/yarp-openmct/issues/43#issuecomment-1275113568.

**Comment by nunoguedelha** [comment]
Updated the estimate to **5**.

**Comment by nunoguedelha** [comment]
## Telemetry Entries not Clickable...

### Vue.js Debugging

We observe the click event handling when e click on an telemetry entry.

**Successful case:** if we click on the the entry `iCub Telemetry->IMU sensors->Legacy IMU sensor measurements`, we get the following function call sequence:
```
handleClick
boundFn
navigateOrPreview
navigate
handleLocationChange
doPathChange
```

<details>
<summary>Details on sequence ending...</summary>

https://github.com/nasa/openmct/blob/ab7e2c57470d3c6076459ad7e3eaa1883cc3b8b0/src/ui/router/ApplicationRouter.js#L300-L318

```
    /**
     * @private
     * Compare new and old path and on change emit event 'change:path'
     *
     * @param {string} newPath new path of url
     * @param {string} oldPath old path of url
     */
    doPathChange(newPath, oldPath) {
        if (newPath === oldPath) {
            return;
        }


        let route = this.routes.filter(r => r.matcher.test(newPath))[0];
        if (route) {
            route.callback(newPath, route.matcher.exec(newPath), this.currentLocation.params);
        }

        this.emit('change:path', newPath, oldPath);
    }
```

</details>

The full function `doPathChange` is executed and the `change:path` event is emitted.

**Failing case:** Instead, if we click on the the entry `iFeel Suit Telemetry->Accelerometers->iFeelSuit::acc::Node#10`, we get the same function call sequence as before, but with a different execution in the last function call `doPathChange`.

https://github.com/nasa/openmct/blob/ab7e2c57470d3c6076459ad7e3eaa1883cc3b8b0/src/ui/router/ApplicationRouter.js#L300-L318

```
    /**
     * @private
     * Compare new and old path and on change emit event 'change:path'
     *
     * @param {string} newPath new path of url
     * @param {string} oldPath old path of url
     */
    doPathChange(newPath, oldPath) {
        if (newPath === oldPath) {
            return;
        }

        let route = this.routes.filter(r => r.matcher.test(newPath))[0];
        if (route) {
            route.callback(newPath, route.matcher.exec(newPath), this.currentLocation.params); <-------- (*)
        }

        this.emit('change:path', newPath, oldPath);
    }
```

(*) The route to the new path never returns and times out and the event `change:path` is never emitted.

This is due to the fact that the routed path was `/browse/yarpopenmct:iFeelSuitTelemetry/yarpopenmct:iFeelSuitTelemetry.accSens/yarpopenmct:iFeelSuitTelemetry.accSens.iFeelSuit::acc::Node` where `#10` is missing.

That last segment was truncated in `handleLocationChange` by the `URL` function:
https://github.com/nasa/openmct/blob/ab7e2c57470d3c6076459ad7e3eaa1883cc3b8b0/src/ui/router/ApplicationRouter.js#L355
```
   let newLocation = this.createLocation(pathString);
```

https://github.com/nasa/openmct/blob/ab7e2c57470d3c6076459ad7e3eaa1883cc3b8b0/src/ui/router/ApplicationRouter.js#L287-L290
```
   let url = new URL(
       pathString,
       `${location.protocol}//${location.host}${location.pathname}`
   );
```

**For allowing a free naming of the iFeel suit sensors, while avoiding such issues, we'll use just numbers as the last segment of the domain object keys.**

**Comment by nunoguedelha** [comment]
## Complete the folders child entry IDs retrieval implementation

- We create a wearable metadata route (sub-server) in the telemetry server
  for fulfilling the folder child entries list requests from the client app.
- Folder child entry keys are requested by the Composition Provider invoked
  for a given folder by the Open-MCT ObjectAPI.
- A request of the folder child entry keys is composed as follows:
  `http://<telem-server-address-host>:<telem-server-address-port>/wearableMetadata/<folder-domain-object-key(s)>/childTelemEntryKeys`
  The request can target a single folder or a comma separated set of folder.
- Telemetry entry names are requested by the Object Provider invoked for the
  folder sub-entries by the Open-MCT ObjectAPI.
- A request of Telemetry entry names is composed as follows:
  `http://<telem-server-address-host>:<telem-server-address-port>/wearableMetadata/<folder-domain-object-key(s)>/<entry-key(s)>/name`
  The request targets a single folder but can target a single entry key or a
  comma separated set of entry keys in that folder.

## Result

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/6848872/197720569-8d46421e-a985-4471-903c-077014c90f13.png">

Here we replayed with the **yarpdataplayer** the dataset [ifeel_data.zip](https://github.com/ami-iit/yarp-openmct/files/9714389/ifeel_data.zip)  twice to trigger tje pipeline but we were only sending dummy data to the visualizer client.

Implemented in 927ae72d10742028e03cda16db1d3c318fa24162.

**Comment by nunoguedelha** [comment]
## Complete the telemetry sample parsing

- The producer name `iFeelSuit::` is parsed (`sensorSample[0]`) but not used nor transmitted to the client visualiser for now as it is not required and appears anyway as a namespace in the sensor names.
- In `WearableDataParser`, we replace the `telemKeyTree` structure of key-value pairs into a `Map` which remembers the insertion order of the keys. This is important for mapping properly the sensor modality array in the telemetry sample. Refer to the **WearableData.thrift** structure:
https://github.com/robotology/wearables/blob/b9a6fe404b837e1b594c89ac1a1ac37dd46a1567/msgs/thrift/WearableData.thrift#L173-L191
  ```
  struct WearableData {
  1: required string producerName;
  2: optional map<string,Accelerometer> accelerometers;
  3: optional map<string,EmgSensor> emgSensors;
  4: optional map<string,Force3DSensor> force3DSensors;
  5: optional map<string,ForceTorque6DSensor> forceTorque6DSensors;
  6: optional map<string,FreeBodyAccelerationSensor> freeBodyAccelerationSensors;
  7: optional map<string,Gyroscope> gyroscopes;
  8: optional map<string,Magnetometer> magnetometers;
  9: optional map<string,OrientationSensor> orientationSensors;
  10: optional map<string,PoseSensor> poseSensors;
  11: optional map<string,PositionSensor> positionSensors;
  12: optional map<string,SkinSensor> skinSensors;
  13: optional map<string,TemperatureSensor> temperatureSensors;
  14: optional map<string,Torque3DSensor> torque3DSensors;
  15: optional map<string,VirtualLinkKinSensor> virtualLinkKinSensors;
  16: optional map<string,VirtualJointKinSensor> virtualJointKinSensors;
  17: optional map<string,VirtualSphericalJointKinSensor> virtualSphericalJointKinSensors;
  }
  ```
- Each optional[^1] line `i` (`i` $\in [2,17]$) of the above structure is a map matching a nested array `sensorSample[i][]` of sensors of same modality, so let `i` be the modality index . Below, `sensorSample[1][]` is an array of 10 accelerometers which implements the `map` of accelerometers::
  ```
  2: optional map<string,Accelerometer> accelerometers;
  ```
  ![image](https://user-images.githubusercontent.com/6848872/198400684-117a6cf2-bae9-4bbf-ae3b-b4ddf796f387.png)
- Each of the `Map` `telemKeyTree` entries has a respective index which matches the modality index `i`. E.g. `"iFeelSuitTelemetry.accSens"` matches modality index 0.

**Comment by nunoguedelha** [comment]
## Test and Issues

Tested https://github.com/ami-iit/yarp-openmct/files/9714389/ifeel_data.zip and found the following issues:
- No data is plotted for entries `Free Body Acceleration Sensors` and `Orientation Sensors`.
- In entry `Virtual Link Kinetic Sensors`, plot appears different between X, Y and Z components of each modality, but seems to be the same between modalities, which would be wrong.

**Comment by nunoguedelha** [comment]
## Analysis

### Reference Object API call sequence

E.g. for the entry `iFeelSuit::gyro::Node#1`, we get the sequence:
``` 
-> navigateToPath(identifier)
	-> pathToObjects(identifier)
		-> migrate(identifier)
			-> openmct.objects.get(identifier)
				-> provider.get(identifier)
```

For the `identifier.key` iteratively equal to `iFeelSuitTelemetry`, `iFeelSuitTelemetry.gyroSens`, `iFeelSuitTelemetry.gyroSens.0`, which follows the decomposition of the last object path. Subsequently, we get the sequence:
```
-> getOriginalPath(iFeelSuitTelemetry.gyroSens.0)
	-> migrate(iFeelSuitTelemetry.gyroSens.0)
		-> ...
	-> getOriginalPath(domainObject.location = iFeelSuitTelemetry)
		-> migrate(iFeelSuitTelemetry)
			-> ...
		-> getOriginalPath(domainObject.location = ROOT)
			-> migrate(ROOT)
				-> ...
```

### Faulty Object API call sequence

For the entry `iFeelSuit::fbAcc::Node#1`, only the first sequence is executed for each of the domain objects in the path:
``` 
-> navigateToPath(identifier)
	-> pathToObjects(identifier)
		-> migrate(identifier)
			-> openmct.objects.get(identifier)
				-> provider.get(identifier)
```

The call sequence initiating in ` getOriginalPath()` does not occur. The problem occurs in between.

We then look into the domain object returned by the `ObjectProvider` for the object `iFeelSuitTelemetry.FBaccSens.0`. We can see in the below image that the returned `result` has wrong content in `telemetry.values`.

![image](https://user-images.githubusercontent.com/6848872/198847331-6b631aef-8062-4f56-b064-8aac0d1a1e54.png)

That is probably the cause preventing the execution sequence that should have followed.

**Comment by nunoguedelha** [comment]
## Analysis Issue 1 ...continued

`dictionary.presetValuesBase` has wrong content for keys `FBaccSens`, `orientSens` and `positionSens`.
```json
{
  "presetValuesBase": {
    "FBaccSens": "[object Object],[object Object],[object Object]"
    "orientSens": "[object Object],[object Object],[object Object],[object Object]"
    "positionSens": "[object Object],[object Object],[object Object]"
  }
}
```
There was a `JSON.stringify()` missing for those entries.

Fixed in 7e980cb7cced49b5902c71f97b9b09506ed59792.

**Comment by nunoguedelha** [comment]
## Analysis Issue 2

For instance, `value.oriQuat.w`, `value.pos.x`, `value.linearVel.x` are always identical.

- This can already be observed on the sample received on the client side:
https://github.com/ami-iit/yarp-openmct/blob/45035b8cda4af25310d1f352196da692f9912e5e/openmctStaticServer/plugins/realtime-telemetry-plugin.js#L10

- The sample data received by the telemetry server is ok, as well as the parser input
https://github.com/ami-iit/yarp-openmct/blob/7e980cb7cced49b5902c71f97b9b09506ed59792/iCubTelemVizServer/wearableDataParser.js#L32

- The issue is in this section, where we don't select the proper elements of `sensorData`:
  https://github.com/ami-iit/yarp-openmct/blob/7e980cb7cced49b5902c71f97b9b09506ed59792/iCubTelemVizServer/wearableDataParser.js#L62-L77

Fixing...

**Comment by nunoguedelha** [comment]
Optimised wearable data parsing in 75a4b570170f3ba6d47878465911a63cc935be03 and 390b246cd628a1aff415d0375d935706f48dd28e. Refer to commit comments for further details.

The goal was to:
- move most of the parsing code to the parser anonymous functions which are faster than regular functions
- build those anonymous functions in the `WearableDataParser` constructor which is executed once at initialisation.

This allows to execute, in the anonymous functions, lines like:
```js
[parsedData.oriQuat.w,parsedData.oriQuat.x,parsedData.oriQuat.y,parsedData.oriQuat.z,parsedData.pos.x,parsedData.pos.y,parsedData.pos.z,parsedData.linearVel.x,parsedData.linearVel.y,parsedData.linearVel.z,parsedData.angVel.x,parsedData.angVel.y,parsedData.angVel.z,parsedData.linearAcc.x,parsedData.linearAcc.y,parsedData.linearAcc.z,parsedData.angAcc.x,parsedData.angAcc.y,parsedData.angAcc.z] = sensorData;
```
directly mapping the `sensorData` table elements to the fields of `parsedData`, instead of iteratively parsing the quaternion data, then the position, linear velocity, etc. Such line is not hardcode, but instead generated in the constructor from the structure `WearableDataParser.telemKeyTree`.

**Comment by nunoguedelha** [comment]
Work complete.

CC @S-Dafarra @RiccardoGrieco
