### ISSUE TITLE
Check server installation on WSL

### ISSUE THREAD

**Issue by RiccardoGrieco** [ami-iit/yarp-openmct#47]
The purpose of this issue is trying to install the server application on Windows Subsystem for Linux ([WSL](https://docs.microsoft.com/en-us/windows/wsl/install),[Ubuntu on WSL](https://ubuntu.com/wsl)).

**Comment by RiccardoGrieco** [comment]
Server seems to be working on WSL!

![image](https://user-images.githubusercontent.com/26788384/142633599-21f4407e-a76b-46b8-b82d-61924b46e0a0.png)

I just rapidly tried running the visualization server and check if it was accessed by the browser. Probably additional tests should be done.

NOTE: for the installation I encountered some issues when running `npm install`. I then found out that `make` was not installed (I supposed it was installed by `mamba install -c robotology compilers cmake`

**Comment by nunoguedelha** [comment]
We could discuss in the next vertical meeting how we wish to proceed with the support of the application on Windows. It depends, among other things, if @RiccardoGrieco or someone else could do some short regression tests of the `main` branch on Windows.

We could eventually add in the main README an installation/run section for Windows with a disclaimer that we don't guarantee a full functionality. After clarifying this, we could then close this issue.

What do you think @traversaro @RiccardoGrieco @S-Dafarra ?

**Comment by traversaro** [comment]
> 

Ok for me!

**Comment by S-Dafarra** [comment]
I don't know if it is worth doing that manually. Testing things in person is still error-prone. We can mention it has been tested in WSL, if we want to support this option. Otherwise, we can consider it as an internal option to be considered if we need the server to run on Windows in the future.

**Comment by nunoguedelha** [comment]
Sure, automatic regression testing is always preferable. I wasn't clear, I didn't mean systematic regression tests, just from time to time, or for some major `yarp-openmct` release, run some tests, and mention in the release the tested platforms.

Regarding automatic testing, I don't know what is possible to do with Github actions, but in any case, although we can define in detail some regression test procedure, I doesn't seem trivial to me to execute to programmatically the interactions with the browser GUI. We can further discuss in the vertical meeting anyway.

**Comment by S-Dafarra** [comment]
> Regarding automatic testing, I don't know what is possible to do with Github actions, but in any case, although we can define in detail some regression test procedure, I doesn't seem trivial to me to execute to programmatically the interactions with the browser GUI.

That is true. In general, for GUI it might not be straightforward to define tests. I wonder whether some tool is available given how Node,js is widespread

**Comment by nunoguedelha** [comment]
Note that on the Client side, the Javascript or HTML code is running on the browser. Node.js is an environment for running Javascript directly on the OS of your machine, while using the runtime engine V8  (same as Chrome browser). I'll check with Open MCT how they test their platform.

**Comment by RiccardoGrieco** [comment]
PR #88 was closed. This issue can be closed too.
